/**
 * Total drill moves per opening (realm), generated by scripts/compute-realm-totals.mjs.
 * Used for per-realm progress meters. DO NOT EDIT MANUALLY.
 */
export const REALM_TOTAL_MOVES: Record<string, number> = {
  "germany": 63,
  "dutch": 47,
  "english": 67,
  "italian": 183,
  "french": 76,
  "queendom": 90,
  "spanish": 66,
  "scandinavian": 63,
  "sicilian": 174
};
