/**
 * Total drill moves per opening (realm), generated by scripts/compute-realm-totals.mjs.
 * Used for per-realm progress meters. DO NOT EDIT MANUALLY.
 */
export const REALM_TOTAL_MOVES: Record<string, number> = {
  "germany": 28,
  "dutch": 14,
  "english": 32,
  "italian": 157,
  "french": 42,
  "queendom": 90,
  "spanish": 66,
  "scandinavian": 47,
  "sicilian": 174
};
